name: react-dart_perf
version: 0.0.1
description: React-Dart Perf
dependencies:
  browser: any
  react:
    git:
      url: git@github.com:greglittlefield-wf/react-dart.git
      ref: ff42e44ed4080b6bb2c5c2f9b3714f9b77699ebd
